### PR TITLE
Fix/add contact page bugs

### LINKED ISSUE #108: Bug - New Contact Doesn't Appear Until Refresh of Home View
Fix AddContact mutation bug

### PR DESCRIPTION
**Pull request by carolineshowscode**
## Type of Change
- [ ] JSX
- [ ] HTML
- [ ] JavaScript
- [ ] CSS
- [ ] React
- [ ] React Router
- [ ] Cypress
- [x] Apollo
- [x] GraphQL
- [ ] Twilio API
- [x] Refactor/Fix Bugs

## Please give a short description of the changes that were made below

- Fix:
- `AddContact.js` was not loading new contact within `Form.js` unless you refreshed the page
- Required further research, and attempted multiple approaches. The most efficient way to fetch the new mutation data was by updating the cache, unfortunately documentation on the matter was confusing and the implemented approach did not work
- Utilized the `refetchQueries` API to fetch the data with the new mutation
- This is still a best practice, and recommended for those new to GraphQL/Apollo  
- In the future, implementing an update function for the cache will be the best way to go as this does not require another network request

- Feature:

## How has this been tested?
- [x] In Browser
- [x] In Console
- [ ] Cypress
- [ ] Postman

### CODE REVIEW

File: src/Components/AddContact/AddContact.js [hunk 1]
```diff
@@ -43,7 +58,10 @@ function AddContact({ user, switchTheme }) {
     setValidCheck(false);
     setPhoneVerify(false);
     let number = `+${countryCode}${areaCode}${phoneNumber}`;
-    createContact( {variables: { firstName: firstName, lastName: lastName, phoneNumber: number}});
+    createContact({
```
Comment (pcmueller) [inline src/Components/AddContact/AddContact.js:61]: Nice work researching how to solve this with refetchQueries!!

**Review by pcmueller — APPROVED** [review]
Thanks for figuring this out - looks great!

File: src/Components/AddContact/AddContact.js [hunk 2]
```diff
@@ -17,6 +17,21 @@ const CREATE_CONTACT = gql`
...
 `
 
+const GET_USER = gql`
+query GetUser {
+  oneUser(id: 2) {
+    firstName
+    lastName
+    username
+    contacts {
+      firstName
```
Comment (bhohnco) [inline src/Components/AddContact/AddContact.js:27]: Nice work running with this!!

**Review by bhohnco — APPROVED** [review]
